import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Overlay from "@/components/Overlay";
const inter = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="min-h-full">
      <body className="min-h-screen">
        <Overlay />
        <div className={`min-h-screen ${inter.className}`}>{children}</div>
      </body>
    </html>
  );
}
