import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Overlay from "@/components/Overlay";
// import ContextWrapper, { wrapperType } from "@/contexts/ContextWrapper";
import CursorProvider from "@/contexts/cursor";
import DarkModeProvider from "@/contexts/darkMode";
const inter = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="min-h-full">
      <body className="min-h-screen">
        {/* <Overlay /> */}
        <DarkModeProvider>
          <CursorProvider>
            {/* <ContextWrapper contextType={wrapperType.CursorContext}> */}
            <div className={`min-h-screen ${inter.className}`}>{children}</div>
            {/* </ContextWrapper> */}
          </CursorProvider>
        </DarkModeProvider>
      </body>
    </html>
  );
}
